export const CartActionTypes = {
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  DECREASE_ITEM_QTY: 'DECREASE_ITEM_QTY',
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  CLEAR_CART: 'CLEAR_CART',
  PAYMENT_SUBMIT_START: 'PAYMENT_SUBMIT_START',
  PAYMENT_SUBMIT_SUCCESS: 'PAYMENT_SUBMIT_SUCCESS',
  PAYMENT_SUBMIT_FAILURE: 'PAYMENT_SUBMIT_FAILURE',
  CLEAR_PAYMENT_STATUS: 'CLEAR_PAYMENT_STATUS'
};
